name: lig_sst
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.22
  - pandas
  - pip
  - scipy 
  - matplotlib
  - seaborn
  - xarray 
  - netCDF4
  - cartopy
  - cfgrib 
  - pathlib 
  - openpyxl